import Head from "next/head";
import { Inter } from "@next/font/google";
import Header from "../../components/Header";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";
import CheckoutSuccess from "../../components/CheckoutSuccess";
import SecondaryHeader from "../../components/SecondaryHeader";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>HIRA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Navbar></Navbar> */}
      {/* <SecondaryHeader></SecondaryHeader> */}
      <Header></Header>
      <CheckoutSuccess></CheckoutSuccess>
      <Footer></Footer>
    </>
  );
}
