import Head from "next/head";
import { Inter } from "@next/font/google";
import Header from "../../components/Header";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";
import RingSettings from "../../components/RingSettings";
import Stepper from "../../components/Stepper";
import MetalSelector from "../../components/MetalSelector";
import SingleShapeSelector from "../../components/SingleShapeSelector";
import Breadcrumb from "../../components/BreadCrumb";
import { navigationBreadCrums } from "../../components/constants";
import DiamondSelectedNotification from "../../components/DiamondSelectedNotification";
import MobileMenu from "../../components/MobileMenu";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>HIRA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative">
        <Navbar></Navbar>
        <Header></Header>
        <MobileMenu></MobileMenu>
      </div>
      <div className="mx-4">
        <Breadcrumb navDetails={navigationBreadCrums["Diamonds"]}></Breadcrumb>
        <DiamondSelectedNotification></DiamondSelectedNotification>
        <Stepper stage={1}></Stepper>
        <SingleShapeSelector singular={true}></SingleShapeSelector>
        <MetalSelector></MetalSelector>
        <RingSettings></RingSettings>
      </div>
      <Footer></Footer>
    </>
  );
}
