import Head from "next/head";
import { Inter } from "@next/font/google";
import Header from "../../components/Header";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";
import RingSettings from "../../components/RingSettings";
import Stepper from "../../components/Stepper";
import MetalSelector from "../../components/MetalSelector";
import SingleShapeSelector from "../../components/SingleShapeSelector";
import Breadcrumb from "../../components/BreadCrumb";
import {
  hiralightGrayBGMD,
  navigationBreadCrums,
} from "../../components/constants";
import DiamondSelectedNotification from "../../components/DiamondSelectedNotification";
import MobileMenu from "../../components/MobileMenu";
import RingSizePicker from "../../components/RingSizePicker";
import SecondaryHeader from "../../components/SecondaryHeader";
import LiveExpertBanner from "../../components/LiveExpertBanner";
import RingKaratPicker from "../../components/RingKaratPicker";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>HIRA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LiveExpertBanner></LiveExpertBanner>
      <div className="relative">
        <Navbar></Navbar>
        <SecondaryHeader></SecondaryHeader>
        <MobileMenu></MobileMenu>
      </div>
      <div className={`mx-4 `}>
        <DiamondSelectedNotification></DiamondSelectedNotification>
      </div>
      <div className={`mx-4 lg:hidden`}>
        <Breadcrumb navDetails={navigationBreadCrums["Diamonds"]}></Breadcrumb>
        <Stepper stage={1}></Stepper>
      </div>
      <div className={`lg:flex lg:h-screen`}>
        <div className={`${hiralightGrayBGMD}`}>
          <div className={`mx-4`}>
            <SingleShapeSelector singular={true}></SingleShapeSelector>
            <MetalSelector></MetalSelector>
            <div className="hidden lg:block">
              <RingSizePicker></RingSizePicker>
              <RingKaratPicker></RingKaratPicker>
            </div>
          </div>
        </div>
        <div className={`mx-4 lg:overflow-y-scroll`}>
          <div className="hidden lg:block w-full">
            <div className="">
              <Stepper stage={1} />
            </div>
          </div>
          <RingSettings></RingSettings>
        </div>
      </div>
      <Footer></Footer>
    </>
  );
}
