import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Header from "../../components/Header";
import Hero from "../../components/Hero";
import Navbar from "../../components/Navbar";
import FAQ from "../../components/FAQ";
import Testimonials from "../../components/Testimonials";
import Footer from "../../components/Footer";
import RingSettings from "../../components/RingSettings";
import Testimony from "../../components/Testimony";
import Gallery from "../../components/Gallery";
import Stepper from "../../components/Stepper";
import ShapeSelector from "../../components/ShapeSelector";
import MetalSelector from "../../components/MetalSelector";
import SingleShapeSelector from "../../components/SingleShapeSelector";
import Breadcrumb from "../../components/BreadCrumb";
import { navigationBreadCrums } from "../../components/constants";
import DiamondSelectedNotification from "../../components/DiamondSelectedNotification";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>HIRA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <Header></Header>
      <Breadcrumb navDetails={navigationBreadCrums["Diamonds"]}></Breadcrumb>
      <DiamondSelectedNotification></DiamondSelectedNotification>
      <Stepper stage={1}></Stepper>
      <div className="flex justify-center">
        <SingleShapeSelector singular={true}></SingleShapeSelector>
      </div>
      <div className="mt-3">
        <MetalSelector></MetalSelector>
      </div>
      <RingSettings></RingSettings>
      <Footer></Footer>
    </>
  );
}
