import Head from "next/head";
import { Inter } from "@next/font/google";
import Header from "../../components/Header";
import Hero from "../../components/Hero";
import FAQ from "../../components/FAQ";
import Testimonials from "../../components/Testimonials";
import NavBar from "../../components/Navbar";
import Footer from "../../components/Footer";
import MobileMenu from "../../components/MobileMenu";
import LiveExpertBanner from "../../components/LiveExpertBanner";
import {
  borderHiraBlack,
  hiraBlackBG,
  hiraWhiteBG,
  shapes,
} from "../../components/constants";
import SanityImages from "../../components/SanityImages";

const inter = Inter({ subsets: ["latin"] });
const speakButton = (
  <div
    className={`flex w-full justify-center py-2 text-black ${hiraWhiteBG} border ${borderHiraBlack} focus:outline-none active:bg-black focus:bg-black text-lg mb-2 hover:cursor-pointer`}
  >
    Speak to an expert
  </div>
);

export default function Home() {
  return (
    <>
      <Head>
        <title>HIRA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LiveExpertBanner></LiveExpertBanner>
      <div className="relative">
        <NavBar></NavBar>
        <Header></Header>
        <MobileMenu></MobileMenu>
      </div>
      <div
        className={`w-screen ${hiraBlackBG} text-white text-center font-Raleway`}
      >
        <div className="p-10">
          <h1 className="mb-4 font-bold text-4xl">Our Story</h1>
          <div>
            Our ancestry of goldsmiths has inspired us to take our family
            business digital. Ever since 1949, our mission has been to deliver
            fine crafted jewelery.
          </div>
        </div>
      </div>

      <div
        className={`w-screen ${hiraWhiteBG} text-black text-center font-Raleway`}
      >
        <div className="p-10 lg:flex">
          <div>
            <SanityImages
              type={"Lifestyle"}
              className=" w-screen pt-3 md:w-full h-auto md:h-[60vh] lg:h-[80vh] justify-center items-center transition-shadow ease-in-out duration-300 shadow-none hover:shadow-xl -z-[10] md:px-5 object-cover"
            ></SanityImages>
          </div>
          <div className="lg:w-3/4">
            <h1 className="mb-4 font-bold text-4xl flex justify-center">
              By your side.
            </h1>
            <div className="text-justify">
              Our ancestry of goldsmiths has inspired us to take our family
              business digital. Ever since 1949, our mission has been to deliver
              fine crafted jewelery. Our ancestry of goldsmiths has inspired us
              to take our family business digital. Ever since 1949, our mission
              has been to deliver fine crafted jewelery. Our ancestry of
              goldsmiths has inspired us to take our family business digital.
              Ever since 1949, our mission has been to deliver fine crafted
              jewelery. Our ancestry of goldsmiths has inspired us to take our
              family business digital. Ever since 1949, our mission has been to
              deliver fine crafted jewelery. Our ancestry of goldsmiths has
              inspired us to take our family business digital. Ever since 1949,
              our mission has been to deliver fine crafted jewelery. Our
              ancestry of goldsmiths has inspired us to take our family business
              digital. Ever since 1949, our mission has been to deliver fine
              crafted jewelery. Our ancestry of goldsmiths has inspired us to
              take our family business digital. Ever since 1949, our mission has
              been to deliver fine crafted jewelery. Our ancestry of goldsmiths
              has inspired us to take our family business digital. Ever since
              1949, our mission has been to deliver fine crafted jewelery.
            </div>
          </div>
        </div>
      </div>

      <div
        className={`w-screen ${hiraBlackBG} text-white text-center font-Raleway`}
      >
        <div
          className={`w-screen ${hiraBlackBG} text-white text-center font-Raleway`}
        >
          <div className="p-10">
            <h1 className="mb-4 font-bold text-4xl">Our Pillars</h1>
            <div>
              Our ancestry of goldsmiths has inspired us to take our family
              business digital. Ever since 1949, our mission has been to deliver
              fine crafted jewelery.
            </div>
          </div>
        </div>
      </div>
      <div
        className={`w-screen ${hiraWhiteBG} text-black text-center font-Raleway`}
      >
        <div className="p-10">
          {/* <h1 className="mb-4 font-bold text-4xl flex justify-center">
            Our Values
          </h1> */}
          <div className="lg:flex lg:text-center lg:items-center lg:justify-center">
            <div>
              <h1 className="mb-4 font-bold text-2xl justify-center">
                <div className="flex justify-center py-4">
                  {shapes.round.svg}
                </div>
                Our Why
              </h1>
              <div className="lg:mx-2">
                Our ancestry of goldsmiths has inspired us to take our family
                business digital. Ever since 1949, our mission has been to
                deliver fine crafted jewelery.
              </div>
            </div>
            <div>
              <h1 className="mb-4 font-bold text-2xl justify-center">
                <div className="flex justify-center py-4">
                  {shapes.round.svg}
                </div>
                Our Vision
              </h1>
              <div className="lg:mx-2">
                Our ancestry of goldsmiths has inspired us to take our family
                business digital. Ever since 1949, our mission has been to
                deliver fine crafted jewelery.
              </div>
            </div>

            <div>
              <h1 className="mb-4 font-bold text-2xl justify-center">
                <div className="flex justify-center py-4">
                  {shapes.round.svg}
                </div>
                Our Mission
              </h1>
              <div className="lg:mx-2">
                Our ancestry of goldsmiths has inspired us to take our family
                business digital. Ever since 1949, our mission has been to
                deliver fine crafted jewelery.
              </div>
            </div>
          </div>
        </div>
      </div>
      <div
        className={`w-screen ${hiraWhiteBG} text-black text-center font-Raleway`}
      >
        <h1 className="my-4 font-bold text-4xl">Our Values</h1>
        <div className="p-10 lg:flex">
          {/* PT 1 */}
          <div>
            <SanityImages
              type={"Lifestyle"}
              className="w-screen md:w-full h-auto md:h-[60vh] lg:h-[80vh] justify-center items-center transition-shadow ease-in-out duration-300 shadow-none hover:shadow-xl -z-[10] md:px-5 object-cover"
            ></SanityImages>
          </div>
          <div className="lg:w-3/4">
            <h1 className="mb-4 font-bold text-2xl flex justify-center text-justify">
              By your side.
            </h1>
            <div className="text-justify">
              Our ancestry of goldsmiths has inspired us to take our family
              business digital. Ever since 1949, our mission has been to deliver
              fine crafted jewelery. Our ancestry of goldsmiths has inspired us
              to take our family business digital. Ever since 1949, our mission
              has been to deliver fine crafted jewelery. Our ancestry of
              goldsmiths has inspired us to take our family business digital.
              Ever since 1949, our mission has been to deliver fine crafted
              jewelery. Our ancestry of goldsmiths has inspired us to take our
              family business digital. Ever since 1949, our mission has been to
              deliver fine crafted jewelery. Our ancestry of goldsmiths has
              inspired us to take our family business digital. Ever since 1949,
              our mission has been to deliver fine crafted jewelery. Our
              ancestry of goldsmiths has inspired us to take our family business
              digital. Ever since 1949, our mission has been to deliver fine
              crafted jewelery. Our ancestry of goldsmiths has inspired us to
              take our family business digital. Ever since 1949, our mission has
              been to deliver fine crafted jewelery. Our ancestry of goldsmiths
              has inspired us to take our family business digital. Ever since
              1949, our mission has been to deliver fine crafted jewelery.
            </div>
            {speakButton}
          </div>
        </div>
        <div className="p-10 lg:flex">
          {/* P2 1 */}
          <div className="lg:w-3/4">
            <h1 className="mb-4 font-bold text-2xl flex justify-center">
              By your side.
            </h1>
            <div className="text-justify">
              Our ancestry of goldsmiths has inspired us to take our family
              business digital. Ever since 1949, our mission has been to deliver
              fine crafted jewelery. Our ancestry of goldsmiths has inspired us
              to take our family business digital. Ever since 1949, our mission
              has been to deliver fine crafted jewelery. Our ancestry of
              goldsmiths has inspired us to take our family business digital.
              Ever since 1949, our mission has been to deliver fine crafted
              jewelery. Our ancestry of goldsmiths has inspired us to take our
              family business digital. Ever since 1949, our mission has been to
              deliver fine crafted jewelery. Our ancestry of goldsmiths has
              inspired us to take our family business digital. Ever since 1949,
              our mission has been to deliver fine crafted jewelery. Our
              ancestry of goldsmiths has inspired us to take our family business
              digital. Ever since 1949, our mission has been to deliver fine
              crafted jewelery. Our ancestry of goldsmiths has inspired us to
              take our family business digital. Ever since 1949, our mission has
              been to deliver fine crafted jewelery. Our ancestry of goldsmiths
              has inspired us to take our family business digital. Ever since
              1949, our mission has been to deliver fine crafted jewelery.
            </div>
            {speakButton}
          </div>
          <div>
            <SanityImages
              type={"Lifestyle"}
              className="w-screen md:w-full h-auto md:h-[60vh] lg:h-[80vh] justify-center items-center transition-shadow ease-in-out duration-300 shadow-none hover:shadow-xl -z-[10] md:px-5 object-cover"
            ></SanityImages>
          </div>
        </div>
      </div>
      <Footer></Footer>
      {/* Custom Ring Banner Page*/}
    </>
  );
}
