import Head from "next/head";
import { Inter } from "@next/font/google";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";
import FAQ from "../components/FAQ";
import Testimonials from "../components/Testimonials";
import Footer from "../components/Footer";
import MobileMenu from "../components/MobileMenu";
import LiveExpertBanner from "../components/LiveExpertBanner";
import { hiraBlackBG, shapes } from "../components/constants";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>HIRA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LiveExpertBanner></LiveExpertBanner>
      <div className="relative">
        <Navbar></Navbar>
        <Header></Header>
        <MobileMenu></MobileMenu>
      </div>
      <Hero></Hero>
      <div
        className={`w-screen ${hiraBlackBG} text-white text-center font-Raleway`}
      >
        <div className="p-10">
          <h1 className="mb-4 font-bold text-4xl">Our Story</h1>
          <div>
            Our ancestry of goldsmiths has inspired us to take our family
            business digital. Ever since 1949, our mission has been to deliver
            fine crafted jewelery.
          </div>
        </div>
      </div>

      <Testimonials></Testimonials>
      <div
        className={`w-screen ${hiraBlackBG} text-white text-center font-Raleway`}
      >
        <div className="p-10">
          <h1 className="mb-4 font-bold text-4xl flex justify-center">
            Our Values
          </h1>
          <div className="lg:flex lg:text-center lg:items-center lg:justify-center">
            <div>
              <h1 className="mb-4 font-bold text-2xl justify-center">
                <div className="flex justify-center py-4">
                  {shapes.round.svg}
                </div>
                Uncompromised Quality
              </h1>
              <div className="lg:mx-2">
                Our ancestry of goldsmiths has inspired us to take our family
                business digital. Ever since 1949, our mission has been to
                deliver fine crafted jewelery.
              </div>
            </div>
            <div>
              <h1 className="mb-4 font-bold text-2xl justify-center">
                <div className="flex justify-center py-4">
                  {shapes.oval.svg}
                </div>
                Uncompromised Service
              </h1>
              <div className="lg:mx-2">
                Our ancestry of goldsmiths has inspired us to take our family
                business digital. Ever since 1949, our mission has been to
                deliver fine crafted jewelery.
              </div>
            </div>
            <div>
              <h1 className="mb-4 font-bold text-2xl justify-center">
                <div className="flex justify-center py-4">
                  {shapes.pear.svg}
                </div>
                Uncompromised Journey
              </h1>
              <div className="lg:mx-2">
                Our ancestry of goldsmiths has inspired us to take our family
                business digital. Ever since 1949, our mission has been to
                deliver fine crafted jewelery.
              </div>
            </div>
            <div>
              <h1 className="mb-4 font-bold text-2xl justify-center">
                <div className="flex justify-center py-4">
                  {shapes.marquise.svg}
                </div>
                Uncompromised Integrity
              </h1>
              <div className="lg:mx-2">
                Our ancestry of goldsmiths has inspired us to take our family
                business digital. Ever since 1949, our mission has been to
                deliver fine crafted jewelery.
              </div>
            </div>
          </div>
        </div>
      </div>
      <FAQ></FAQ>
      <Footer></Footer>
      {/* Custom Ring Banner Page*/}
    </>
  );
}
