import Head from "next/head";
import { Inter } from "@next/font/google";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";
import FAQ from "../components/FAQ";
import Testimonials from "../components/Testimonials";
import Footer from "../components/Footer";
import MobileMenu from "../components/MobileMenu";
import LiveExpertBanner from "../components/LiveExpertBanner";
import {
  borderHiraBlack,
  hiraBlackBG,
  hiraDarkBrownText,
  hiraLightBrownBG,
  hiraWhite,
  hiraWhiteBG,
  hiralightGrayBG,
  shapes,
} from "../components/constants";
import OurValues from "../components/OurValues";
import WhatsIncluded from "../components/WhatsIncluded";
import SanityImages from "../components/SanityImages";
import SecondaryHeader from "../components/SecondaryHeader";
import Link from "next/link";
import OurPricing from "../components/OurPricing";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>HIRA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LiveExpertBanner></LiveExpertBanner>
      <div className="relative">
        {/* <Navbar></Navbar> */}
        {/* <SecondaryHeader></SecondaryHeader> */}
        <Header></Header>
        <MobileMenu></MobileMenu>
      </div>
      <Hero></Hero>
      <div
        className={`w-screen ${hiralightGrayBG} ${hiraDarkBrownText} text-center`}
      >
        {/* CTA 1 */}
        <div className="px-10 py-20">
          <h1 className="mb-4 font-bold text-center text-4xl">{`The HIRA way.`}</h1>
          <div className="justify-center">
            <div className="md:p-4 md:px-8 text-center text-2xl text-emerald-900">
              {`In business for over 40 years. We provide lifestime warranty, free shipping, free returns, and 100% satisfaction guarantee.`}
            </div>
            <div className="flex justify-center text-center items-center">
              <Link
                href="/about"
                class={`flex w-fit justify-center py-2 px-4 text-white bg-emerald-900 border ${borderHiraBlack} hover:bg-gradient-to-br text-lg md:text-lg mt-8 md:mt-4 mr-2`}
              >
                About Us
              </Link>
              <Link
                href="/custom"
                class={`flex w-fit justify-center py-2 px-4 text-white bg-emerald-900 border ${borderHiraBlack} hover:bg-gradient-to-br text-lg md:text-lg mt-8 md:mt-4`}
              >
                Get started
              </Link>
            </div>
          </div>
        </div>
      </div>
      <div
        className={`w-screen ${hiraWhiteBG} ${hiraDarkBrownText} text-center`}
      >
        {/* CTA 2 */}
        <div className="px-10 md:px-20 py-10">
          <div className="lg:flex">
            <div className="lg:w-1/2 lg:px-6">
              <h1
                className={`mb-4 font-bold text-4xl md:text-4xl md:font-bold text-left text-emerald-900`}
              >{`Authentic materials only.`}</h1>
              <div className="justify-center">
                <div className="text-left text-2xl">
                  {`Solid gold. Certified (IGI, GIA) diamonds only. Choose one our rings, or make a custom for no extra cost.`}
                </div>
                <div className="flex md:justify-start justify-center text-center items-center">
                  <Link
                    href="/how-it-works"
                    class={`flex w-screen md:w-fit justify-center py-2 px-4 text-white bg-emerald-900 border ${borderHiraBlack} text-lg md:text-lg mt-8 mr-2 md:mt-4 mb-8`}
                  >
                    More Details
                  </Link>
                  <Link
                    href="/ringsettings"
                    class={`flex w-screen md:w-fit justify-center py-2 px-4 text-white bg-emerald-900 border ${borderHiraBlack} text-lg md:text-lg mt-8 md:mt-4 mb-8`}
                  >
                    Shop Rings
                  </Link>
                </div>
              </div>
            </div>
            <div className="lg:w-1/2 flex-shrink">
              <SanityImages
                type={"Rings"}
                className="justify-center w-full items-center text-center -z-[10] md:h-[40vh] lg:px-5 object-cover"
                imgIndex={1}
              ></SanityImages>
            </div>
          </div>
        </div>
      </div>
      <div
        className={`w-screen ${hiralightGrayBG} ${hiraDarkBrownText} text-center`}
      >
        {/* CTA 3 */}
        <div className="px-10 md:px-20 py-10">
          <div className="lg:flex">
            <div className="lg:w-1/2 flex-shrink">
              <SanityImages
                type={"Rings"}
                className="justify-center w-full items-center text-center -z-[10] md:h-[40vh] lg:px-5 object-cover"
                imgIndex={0}
              ></SanityImages>
            </div>
            <div className="lg:w-1/2 lg:px-6 mt-4">
              <h1
                className={`mb-4 font-bold text-4xl md:text-4xl md:font-bold text-left text-emerald-900`}
              >{`Pick a style, pick a diamond, checkout.`}</h1>
              <div className="justify-center">
                <div className="text-left text-2xl">
                  {`No hidden pricing, build your ring online and have it shipped in 2-3 weeks.`}
                </div>
                {/* <div className="flex md:justify-start justify-center text-center items-center">
                  <Link
                    href="/contact"
                    class={`flex w-screen md:w-fit justify-center py-2 px-8 text-white bg-emerald-900 border ${borderHiraBlack} text-lg md:text-lg mt-8 md:mt-4 mb-8`}
                  >
                    Our Pricing
                  </Link>
                </div> */}
              </div>
            </div>
          </div>
        </div>
      </div>
      <OurPricing></OurPricing>
      <div className={`${hiralightGrayBG} py-24`}>
        <h1
          className={`mb-4 font-bold text-4xl text-center my-4 md:my-8 text-emerald-900`}
        >
          Our Promise
        </h1>
        <WhatsIncluded></WhatsIncluded>
      </div>
      <Testimonials></Testimonials>
      <OurValues></OurValues>
      <FAQ></FAQ>
      <Footer></Footer>
      {/* Custom Ring Banner Page*/}
    </>
  );
}
