import Head from "next/head";
import { Inter } from "@next/font/google";
import Header from "../../components/Header";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";
import MetalSelector from "../../components/MetalSelector";
import SingleShapeSelector from "../../components/SingleShapeSelector";
import Breadcrumb from "../../components/BreadCrumb";
import { navigationBreadCrums } from "../../components/constants";
import MobileMenu from "../../components/MobileMenu";
import SettingsProductDetail from "../../components/SettingsProductDetail";
import ShippingInfo from "../../components/ShippingInfo";
import RefundPolicy from "../../components/RefundPolicy";
import SettingDetailDescription from "../../components/SettingDetailDescription";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>HIRA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative">
        <Navbar></Navbar>
        <Header></Header>
        <MobileMenu></MobileMenu>
      </div>
      <Breadcrumb navDetails={navigationBreadCrums["Settings"]}></Breadcrumb>
      <SettingsProductDetail></SettingsProductDetail>
      <SingleShapeSelector singular={true}></SingleShapeSelector>
      <div className="mt-3">
        <MetalSelector></MetalSelector>
      </div>
      <SettingDetailDescription></SettingDetailDescription>
      <ShippingInfo></ShippingInfo>
      <RefundPolicy></RefundPolicy>
      <Footer></Footer>
    </>
  );
}
