import Head from "next/head";
import { Inter } from "@next/font/google";
import Header from "../../components/Header";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";
import MetalSelector from "../../components/MetalSelector";
import SingleShapeSelector from "../../components/SingleShapeSelector";
import Breadcrumb from "../../components/BreadCrumb";
import { navigationBreadCrums } from "../../components/constants";
import MobileMenu from "../../components/MobileMenu";
import SettingsProductDetail from "../../components/SettingsProductDetail";
import ShippingInfo from "../../components/ShippingInfo";
import RefundPolicy from "../../components/RefundPolicy";
import SettingDetailDescription from "../../components/SettingDetailDescription";
import RingSizePicker from "../../components/RingSizePicker";
import CTASetting from "../../components/CTASetting";
import SecondaryHeader from "../../components/SecondaryHeader";
import LiveExpertBanner from "../../components/LiveExpertBanner";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>HIRA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LiveExpertBanner></LiveExpertBanner>
      <div className="relative">
        <Navbar></Navbar>
        <SecondaryHeader></SecondaryHeader>
        <MobileMenu></MobileMenu>
      </div>
      <div className="mx-4">
        <Breadcrumb navDetails={navigationBreadCrums["Settings"]}></Breadcrumb>
      </div>
      <div className={`mx-4 lg:flex`}>
        <div className={`lg:flex-grow`}>
          <SettingsProductDetail></SettingsProductDetail>
          <div className={`hidden lg:flex`}>
            <SettingDetailDescription></SettingDetailDescription>
          </div>
        </div>
        <div className={`lg:flex-shrink lg:mx-4`}>
          <SingleShapeSelector singular={true}></SingleShapeSelector>
          <MetalSelector></MetalSelector>
          <RingSizePicker></RingSizePicker>
          <div className={`lg:hidden`}>
            <SettingDetailDescription></SettingDetailDescription>
          </div>
          <ShippingInfo></ShippingInfo>
          <RefundPolicy></RefundPolicy>
          <div className="hidden lg:block">
            <CTASetting></CTASetting>
          </div>
        </div>
      </div>

      <Footer></Footer>
    </>
  );
}
